// Post.h – Specification
#pragma once            // generated by Visual Studio
#include <iostream>     // for input/output
#include <string>       // for string class
#include <ctime>
using namespace std;
class Post
{
// data (properties)
private:
    string title;
    string content;
    string postTime; //not sure if is this format [time_t now = time(0); to get current time]
    string username;

// functions (methods)
public:
    Post();	                      
    Post(string, string, string, string);
    void setPostTitle(string);    
    string getPostTitle();        
    void setPostContent(string);  
    string getPostContent();      
    void setPostTime(string);     
    string getPostTime();
    void setUsername(string);
    string getUsername();
};