// Topic.h – Specification
#pragma once            // generated by Visual Studio
#include <iostream>     // for input/output
#include <string>       // for string class
#include <ctime>
using namespace std;
class Post
{
// data (properties)
private:
    string title;
    string content;
    time_t postTime; //not sure if is this format [time_t now = time(0); to get current time]

// functions (methods)
public:
    Post();	                        // default constructor
    Post(string, string, time_t);	// parameterized constructor
    void setPostTitle(string);     // set topic name
    string getPostTitle();         // get topic name
    void setPostContent(string);     // set topic name
    string getPostContent();         // get topic name
    void setPostTime(time_t);     // set topic name
    time_t getPostTime();         // get topic name
};