// Reply.h – Specification
#pragma once            // generated by Visual Studio
#include <iostream>     // for input/output
#include <string>       // for string class
//#include <ctime>
using namespace std;
class Reply
{
    // data (properties)
private:
    string content;
    //string replyTime; //not sure if is this format [time_t now = time(0); to get current time]
    string username;

    // functions (methods)
public:
    Reply();
    Reply(string c, string un);
    void setReplyContent(string c);
    string getReplyContent();
    void setUsername(string un);
    string getUsername();
};