// Topic.h – Specification
#pragma once            // generated by Visual Studio
#include <iostream>     // for input/output
#include <string>       // for string class
using namespace std;
class Topic
{
    // data (properties)
private:
    string topicId;
    string title;
    // functions (methods)
public:
    Topic();	                    // default constructor
    Topic(string, string);	        // parameterized constructor
    void setTopicId(string);        // set topic id
    string getTopicId();            // get topic id
    void setTopicTitle(string);     // set topic name
    string getTopicTitle();         // get topic name
};

