// Topic.h – Specification
#pragma once            // generated by Visual Studio
#include <iostream>     // for input/output
#include <string>       // for string class
#include <array>
#include "Post.h"
using namespace std;
class Topic
{
    // data (properties)
private:
    #pragma region topicId
    //string topicId;
    #pragma endregion
    string title;
    //vector <Post> post;

    // functions (methods)
public:
    Topic();	                    // default constructor
    Topic(string);	        // parameterized constructor
    void setTopicTitle(string);     // set topic name
    string getTopicTitle();         // get topic name

    //void addPost(const Post &posts){ post.push_back(posts); }

    #pragma region topicId
    //Topic(string, string);	        // parameterized constructor
    //void setTopicId(string);        // set topic id
    //string getTopicId();            // get topic id
    #pragma endregion 
};

