// Topic.h – Specification
#pragma once            // generated by Visual Studio
#include <iostream>     // for input/output
#include <string>       // for string class
using namespace std;
class Topic
{
    // data (properties)
private:
    string title;
    // functions (methods)
public:
    Topic();	            // default constructor
    Topic(string);	        // parameterized constructor
    void setTopic(string);	// set name
    string getTopic();		// get name
};

